version: "3.7"
services:
  eventsim:
    hostname: eventsim
    stdin_open: true
    tty: true
    container_name: eventsim2
    build:
      context: .
    entrypoint: './entrypoint.sh'
    volumes:
      - ./eventsim:/opt/eventsim/files
    ports:
      - '8888:8888'
      - '9083:9083'
    env_file:
      - 'minio.env'
    networks:
      - trino-network
  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data
    env_file:
      - 'minio.env'
    command: server --console-address ":9001" /data
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge
